WITH AllDays AS (
    SELECT Num FROM Shipments
    UNION ALL
    SELECT 0 UNION ALL
    SELECT 0 UNION ALL
    SELECT 0 UNION ALL
    SELECT 0 UNION ALL
    SELECT 0 UNION ALL
    SELECT 0 UNION ALL
    SELECT 0
),
Ordered AS (
    SELECT 
        Num, 
        ROW_NUMBER() OVER (ORDER BY Num) AS rn
    FROM AllDays
)
SELECT 
    AVG(CAST(Num AS FLOAT)) AS Median
FROM Ordered
WHERE rn IN (20, 21);
